spring.application.name=attendance-management-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/attendance_db?createDatabaseIfNotExists=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

jwt.secret=MM2YBjNOb25EeX69RGOAksOjqCYIuZH+l2jeAZFKhDwk40zdrIGkYaIyX/q9BiuFxrNzFxJpT+8PLPjwPm6rlA
jwt.expiration.ms=86400000

spring.web.cors.allowed-origins=http://localhost:5173
