spring.application.name=attendance-management-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/attendance_db?createDatabaseIfNotExists=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=username #----------IMP-----------

spring.datasource.password=your_database_password #----------IMP-----------

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

jwt.secret=ENTER_KEY_BY_EXECUTING_JwtSecretGenerator.java #----------IMP-----------

jwt.expiration.ms=86400000

spring.web.cors.allowed-origins=http://localhost:5173


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=your_actual_mail_to_receive_otp #----------IMP-----------

spring.mail.password=your-app-password #----------IMP----------- # REPLACE 'your-app-password' with the 16-character App Password from Google

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
