package com.cdac.attendance.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Data
@NoArgsConstructor
public class Lecture {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "faculty_id", nullable = false)
    private User faculty; 

    private String subjectName;

    @Column(nullable = false)
    private LocalDateTime startTime;

    // --- Security Fields ---
    
    private String activeOtp; // The 4-digit code generated by Faculty

    // NEW FIELD: Tracks when the OTP expires
    private LocalDateTime otpExpiryTime; 

    // We store Latitude/Longitude as Double
    private Double latitude; 
    private Double longitude;
    
    // Default radius in meters (e.g., 50.0)
    private Double radius = 50.0; 
    
    public String getSubjectName() { return subjectName; }
    public void setSubjectName(String subjectName) { this.subjectName = subjectName; }
}